@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package org.magicteam.relicsandfoes.world.block.crossrealmancientruins;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
